// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbGLDqygoynEqQF8wwyORnow2lQ5OEGkE',
    appId: '1:237712194644:web:80340ddfb25c392ff481c1',
    messagingSenderId: '237712194644',
    projectId: 'pullman-v2',
    authDomain: 'pullman-v2.firebaseapp.com',
    storageBucket: 'pullman-v2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABRGHM4ryU16mn-SMsN8QHDscS0YED_-A',
    appId: '1:237712194644:android:1c3af897ac4690edf481c1',
    messagingSenderId: '237712194644',
    projectId: 'pullman-v2',
    storageBucket: 'pullman-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNLwDdihIIhC4Cjt0gtKbsqJKkhL7jHbo',
    appId: '1:237712194644:ios:bc017082adecfb2df481c1',
    messagingSenderId: '237712194644',
    projectId: 'pullman-v2',
    storageBucket: 'pullman-v2.firebasestorage.app',
    iosBundleId: 'com.example.pullmanV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNLwDdihIIhC4Cjt0gtKbsqJKkhL7jHbo',
    appId: '1:237712194644:ios:bc017082adecfb2df481c1',
    messagingSenderId: '237712194644',
    projectId: 'pullman-v2',
    storageBucket: 'pullman-v2.firebasestorage.app',
    iosBundleId: 'com.example.pullmanV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbGLDqygoynEqQF8wwyORnow2lQ5OEGkE',
    appId: '1:237712194644:web:903ddc80a3ba77aff481c1',
    messagingSenderId: '237712194644',
    projectId: 'pullman-v2',
    authDomain: 'pullman-v2.firebaseapp.com',
    storageBucket: 'pullman-v2.firebasestorage.app',
  );
}
